use bc_envelope::prelude::*;

mod common;
use common::*;

const SEED: &str = "ur:seed/oyadhdcxhsinuesrennenlhfaopycnrfrkdmfnsrvltowmtbmyfwdafxvwmthersktcpetdweocfztrd";
const PRVKEYS: &str = "ur:crypto-prvkeys/hdcxhsinuesrennenlhfaopycnrfrkdmfnsrvltowmtbmyfwdafxvwmthersktcpetdwfnbndeah";
const COMMENT: &str = "comment";

#[test]
fn test_generate_random_private_key_base() {
    let prvkeys = run_cli(&["generate", "prvkeys"]).unwrap();
    assert_eq!(UR::from_ur_string(prvkeys).unwrap().ur_type_str(), "crypto-prvkeys");
}

#[test]
fn test_generate_private_key_base_from_seed() {
    let prvkeys = run_cli(&["generate", "prvkeys", "--seed", SEED]).unwrap();
    assert_eq!(prvkeys, PRVKEYS);
}

#[test]
fn test_schnorr() {
    let pubkeys = run_cli(&["generate", "pubkeys", PRVKEYS]).unwrap();
    let expected_pubkeys = "ur:crypto-pubkeys/lftanshfhdcxayvazmflzsfrotemfxvoghtbynbsgywztlheisvapypmidzmaoldisdybkvdlerytansgrhdcxfdgwgacloxsrmupdcybdchfylewsdilrbestjodpwnknndjoztjprfkkjopkdejobebtdlhd";
    assert_eq!(pubkeys, expected_pubkeys);

    let signer = run_cli(&["generate", "signer", PRVKEYS]).unwrap();
    let expected_signer = "ur:signing-private-key/hdcxpfsndiahcxsfrhjoltglmebwwnnstovocffejytdbwihdkrtdykebkiebglbtteeimhsvamu";
    assert_eq!(signer, expected_signer);

    let verifier = run_cli(&["generate", "verifier", &signer]).unwrap();
    let expected_verifier = "ur:signing-public-key/hdcxayvazmflzsfrotemfxvoghtbynbsgywztlheisvapypmidzmaoldisdybkvdleryflfzdlia";
    assert_eq!(verifier, expected_verifier);

    let verifier = run_cli(&["generate", "verifier", expected_pubkeys]).unwrap();
    assert_eq!(verifier, expected_verifier);
}

#[test]
fn test_ecdsa() {
    let pubkeys = run_cli(&["generate", "pubkeys", "--type", "ecdsa", PRVKEYS]).unwrap();
    let expected_pubkeys = "ur:crypto-pubkeys/lftanshflfadhdclaoayvazmflzsfrotemfxvoghtbynbsgywztlheisvapypmidzmaoldisdybkvdlerytansgrhdcxfdgwgacloxsrmupdcybdchfylewsdilrbestjodpwnknndjoztjprfkkjopkdejomecapkpr";
    assert_eq!(pubkeys, expected_pubkeys);

    let signer = run_cli(&["generate", "signer", "--type", "ecdsa", PRVKEYS]).unwrap();
    let expected_signer = "ur:signing-private-key/lfadhdcxpfsndiahcxsfrhjoltglmebwwnnstovocffejytdbwihdkrtdykebkiebglbtteecsioludn";
    assert_eq!(signer, expected_signer);

    let verifier = run_cli(&["generate", "verifier", &signer]).unwrap();
    let expected_verifier = "ur:signing-public-key/lfadhdclaoayvazmflzsfrotemfxvoghtbynbsgywztlheisvapypmidzmaoldisdybkvdlerylgstinvl";
    assert_eq!(verifier, expected_verifier);

    let verifier = run_cli(&["generate", "verifier", expected_pubkeys]).unwrap();
    assert_eq!(verifier, expected_verifier);
}

#[test]
fn test_ssh_ed25519() {
    let pubkeys = run_cli(&["generate", "pubkeys", "--type", "ssh-ed25519", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_pubkeys = "ur:crypto-pubkeys/lftanshftanehskshdjkjkisdpihieeyececehescxfpfpfpfpfxeoglknhsfxehjzhtfygaehglghfeecfpfpfpfpgafwemeydlgseseyetendndlhkgdkpeojneseckogridjyjshsflgmjnidjzgdhgiygtgdhsgwhthkemdldyjyiycxiajljnjnihjtjytansgrhdcxfdgwgacloxsrmupdcybdchfylewsdilrbestjodpwnknndjoztjprfkkjopkdejogoimkkkt";
    assert_eq!(pubkeys, expected_pubkeys);

    let signer = run_cli(&["generate", "signer", "--type", "ssh-ed25519", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_signer = "ur:signing-private-key/tanehnkkadmydpdpdpdpdpfwfeflgaglcxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkideofwjzidjtglknhsfxehjphthdjejyieimfefpfpfpfpfpfwfleckoidjngofpfpfpfpfeidjneskphtgyfpfpfpfpfpfpfpfpfpfwfpfpfpfpgtktfpfpfpfpjykniaeyiojyhthgbkgykkglghgoksgwgyfpfpfpfxfpiheskokkdliekogwkokoeyfyemjyeckoihidkkjnemhsjnisjehtjnecghehjtknfyeyimjnhggwdlesgshdktfpfpfpgefyjkeejpgyjlemgwgrdybkgrfpfpfpfpfpjykniaeyiojyhthggykkglghgoksgwgyfpfpfpfxfpiheskokkdliekogwkokoeyfyemjyeckoihidkkjnemhsjnisjehtjnecghehjtknfyeyimjnhggwdlesgshdktbkfpfpfpfefyidiaesjpgdjojpioioidjkkokpiaghgugsjsjlflkphdidiahtecihgyktjsinfxecehfgfykpdygheciegwfwemeydlgseseyetendndlhkgdkpeojneseckogridjyjsbkhsflgmjnidjzgdhgiygtgdhsgwhthkemdldyjyiyfpfpfpfpfweyglkoidhgehjzidjtgyfwfpiogtfefwgyhkfsbkdpdpdpdpdpfeglfycxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkmnfptpeh";
    assert_eq!(signer, expected_signer);

    let verifier = run_cli(&["generate", "verifier", &signer]).unwrap();
    let expected_verifier = "ur:signing-public-key/tanehskshdjkjkisdpihieeyececehescxfpfpfpfpfxeoglknhsfxehjzhtfygaehglghfeecfpfpfpfpgafwemeydlgseseyetendndlhkgdkpeojneseckogridjyjshsflgmjnidjzgdhgiygtgdhsgwhthkemdldyjyiycxiajljnjnihjtjyeyflsegd";
    assert_eq!(verifier, expected_verifier);

    let verifier = run_cli(&["generate", "verifier", expected_pubkeys]).unwrap();
    assert_eq!(verifier, expected_verifier);
}

#[test]
fn test_ssh_ecdsa_nistp256() {
    let pubkeys = run_cli(&["generate", "pubkeys", "--type", "ssh-ecdsa-p256", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_pubkeys = "ur:crypto-pubkeys/lftanshftanehskspdihiaiejkhsdpjkishseydpjtinjkjyjoeyecencxfpfpfpfpfeeyhfimhtfdglisgshdgljlhkghgajyidjnjzkniefdfpkkglghhkfpfpfpfpgaidjnjzkniefdfpkkglghhkfpfpfpfwfwfwflengakpflgygoiajteyeyehgdhkimgwgeihgmgmingeiyiyhtjzjnksfxjkemfwenkphsgsksjtgyeyioeteokohsidjykpehgdihgsiyguenjsjtgojofgjlfggadyjedlgrioetgahdemjyihjpioidjtidkpgajkglgafektfscxiajljnjnihjtjytansgrhdcxfdgwgacloxsrmupdcybdchfylewsdilrbestjodpwnknndjoztjprfkkjopkdejodlztswca";
    assert_eq!(pubkeys, expected_pubkeys);

    let signer = run_cli(&["generate", "signer", "--type", "ssh-ecdsa-p256", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_signer = "ur:signing-private-key/tanehnkkadwpdpdpdpdpdpfwfeflgaglcxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkideofwjzidjtglknhsfxehjphthdjejyieimfefpfpfpfpfpfwfleckoidjngofpfpfpfpfeidjneskphtgyfpfpfpfpfpfpfpfpfpfwfpfpfpfphsfpfpfpfpfwgljzhkeygmknhkgubkehknhsflfekkgshgecjoiaeogmktgtimgoeyfpfpfpfpfxflecjoiaeogmktgtimgoeyfpfpfpfpgygygmkpingsisjefgfdgeesjyjygheygakninhdjegohkinhdeoeyhthtjkgyjpbkgwktihjpjninethtdygljlgdglemeyjnemidjygheoineodykpjsjoehgrgmhsfwguglgegdkkjlgdfxfgdnemhdjseefleceyemingsfygufwgtfpfpfpfpjlgwhggsfxgykojzinktbkjegsfpfpfpfpfeeyhfimhtfdglisgshdgljlhkghgajyidjnjzkniefdfpkkglghhkfpfpfpfpgaidjnjzkniefdfpkkglghhkfpfpfpfwfwfwflengakpflgygoiajteyeyehgdhkimbkgwgeihgmgmingeiyiyhtjzjnksfxjkemfwenkphsgsksjtgyeyioeteokohsidjykpehgdihgsiyguenjsjtgojofgjlfggadyjedlgrioetgahdemjyihjpioidjtidkpgajkglgafebkktfpfpfpfpiofdjeeegreeengtktgleejpeoiaesimjnjtjteyjzglkkghimhkiydnemdlgaghgdindngsiojlkkgoflghfxfpfpfpfpfpfdhkeyesjyidhghfkpiefpfefsbkdpdpdpdpdpfeglfycxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbktynbssur";
    assert_eq!(signer, expected_signer);

    let verifier = run_cli(&["generate", "verifier", &signer]).unwrap();
    let expected_verifier = "ur:signing-public-key/tanehskspdihiaiejkhsdpjkishseydpjtinjkjyjoeyecencxfpfpfpfpfeeyhfimhtfdglisgshdgljlhkghgajyidjnjzkniefdfpkkglghhkfpfpfpfpgaidjnjzkniefdfpkkglghhkfpfpfpfwfwfwflengakpflgygoiajteyeyehgdhkimgwgeihgmgmingeiyiyhtjzjnksfxjkemfwenkphsgsksjtgyeyioeteokohsidjykpehgdihgsiyguenjsjtgojofgjlfggadyjedlgrioetgahdemjyihjpioidjtidkpgajkglgafektfscxiajljnjnihjtjyrhpttnon";
    assert_eq!(verifier, expected_verifier);

    let verifier = run_cli(&["generate", "verifier", expected_pubkeys]).unwrap();
    assert_eq!(verifier, expected_verifier);
}

#[test]
fn test_ssh_ecdsa_nistp384() {
    let pubkeys = run_cli(&["generate", "pubkeys", "--type", "ssh-ecdsa-p384", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_pubkeys = "ur:crypto-pubkeys/lftanshftanehskstyihiaiejkhsdpjkishseydpjtinjkjyjoeoeteecxfpfpfpfpfeeyhfimhtfdglisgshdgljlhkghgajyidjnjzkniefdfpkngwfygyfpfpfpfpgaidjnjzkniefdfpkngwfygyfpfpfpfwisfwfeeedyfgdyksjogrgmgoghhkieidindlgrisfggdjofwihehgwidjohsgsgleojlgwjlflhdhfjehkkoksecgmididkkengdjkiaflgehtemflgtdyingsguihinjojljletkkhdgyemfefwgogmksinflgaingokojliyhgkojyetjzeefggmehfleyksgaiogadyimiefxiseteyfggejkiegoehkkfgimethtiajkgtindlisjnecghdnjthsiofsfscxiajljnjnihjtjytansgrhdcxfdgwgacloxsrmupdcybdchfylewsdilrbestjodpwnknndjoztjprfkkjopkdejoltvdgula";
    assert_eq!(pubkeys, expected_pubkeys);

    let signer = run_cli(&["generate", "signer", "--type", "ssh-ecdsa-p384", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_signer = "ur:signing-private-key/tanehnkkaohtdpdpdpdpdpfwfeflgaglcxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkideofwjzidjtglknhsfxehjphthdjejyieimfefpfpfpfpfpfwfleckoidjngofpfpfpfpfeidjneskphtgyfpfpfpfpfpfpfpfpfpfwfpfpfpfpinfpfpfpfpfwgljzhkeygmknhkgubkehknhsflfekkgshgecjoiaeogmktgtkniodyfpfpfpfpfxflecjoiaeogmktgtkniodyfpfpfpfphkgygmgwglfwiegthsgujehffeeyfdhgeekokkjlgmghengyhdjyghjnenhginknbkieenfyjsfwjzehhtflgsetihgohgeyetkpimemfdfwinhgihksimglgaindyjtjljshsgrgdgtjzdygwksfphffeiahkisingajzgsenfdehjpemiygeihfwgoiegmjyjkgugafxglgabkeogyjliyglisguidfdhfgliaishkdlflhdgsfygakoeehtkpgodljoeyjlfpfpfpfygyioeseefegtgagdihfwfyfpfpfpfpfpghhthggljeiaeyfejyiaeyisisgtinehkphshdgldybkiafygteeglfpfpfpfpfpiskphshdgldyiafygteeglfpfpfpfpflfefeghimgyhdghfljejofggmglisehkpgsetjsfegodnjefgemgoeckpjzjljkeoihioeniohtiehggmindlfdjzbkfgjykogsjldnkskthkjzjtjkhkkngugajygeengrjninimkngeiefyjkgyfggmfdflgahkingegudniseshsdneokkhdiohffdgoididfeinfpimgugldygrfdknhkgojnksehghhdgabkhggdksjzkkktkkgsdnflidjzgdeniejsfpfpfpfpgtgyfxjljejtjygdinidgmfejliaiadlehglioiejofddnhdkojleejpjejehdenglesjyjofldliagrjljkgeisdyjeksjekojybkdyfgihkkesktknhkioehfpetkshtkojseefpfpfpfpfdhkeyesjyidhghfkpiefpfsfsbkdpdpdpdpdpfeglfycxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkkomhbwty";
    assert_eq!(signer, expected_signer);

    let verifier = run_cli(&["generate", "verifier", &signer]).unwrap();
    let expected_verifier = "ur:signing-public-key/tanehskstyihiaiejkhsdpjkishseydpjtinjkjyjoeoeteecxfpfpfpfpfeeyhfimhtfdglisgshdgljlhkghgajyidjnjzkniefdfpkngwfygyfpfpfpfpgaidjnjzkniefdfpkngwfygyfpfpfpfwisfwfeeedyfgdyksjogrgmgoghhkieidindlgrisfggdjofwihehgwidjohsgsgleojlgwjlflhdhfjehkkoksecgmididkkengdjkiaflgehtemflgtdyingsguihinjojljletkkhdgyemfefwgogmksinflgaingokojliyhgkojyetjzeefggmehfleyksgaiogadyimiefxiseteyfggejkiegoehkkfgimethtiajkgtindlisjnecghdnjthsiofsfscxiajljnjnihjtjyaagtkkvo";
    assert_eq!(verifier, expected_verifier);

    let verifier = run_cli(&["generate", "verifier", expected_pubkeys]).unwrap();
    assert_eq!(verifier, expected_verifier);
}

#[test]
fn test_ssh_ecdsa_nistp521() {
    let pubkeys = run_cli(&["generate", "pubkeys", "--type", "ssh-ecdsa-p521", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_pubkeys = "ur:crypto-pubkeys/lftanshftanehskkadaaihiaiejkhsdpjkishseydpjtinjkjyjoeceyehcxfpfpfpfpfeeyhfimhtfdglisgshdgljlhkghgajyidjnjzkniefdfpehgtimfefpfpfpfpgaidjnjzkniefdfpehgtimfefpfpfpfxfgfwfpfegsgmgrktisgdjpflfwfxdnjkemimhgfeisknktgweodlethkgtjeiagwiagygafgidiefphtehgaisguksjogeiehkfygtguhtjpgdidjkgdieenjsjlkpghimksgdgsiaemjehgknjnimjsglkteyiykoglfpjodydyetkpidjygyfpfgkoiygljkjsgafeiejteydninjzfdeohdjtfgglenhkksgajlihgudyidgajsghecfxfgdniykkgeehgrieiegmkpjyiskkehjtgrkkgyknimgddnjpfyeyeeihfgemghgmgogwhfghkpinhgjpeoiykpdyiydyktimgaehjygygyfsfscxiajljnjnihjtjytansgrhdcxfdgwgacloxsrmupdcybdchfylewsdilrbestjodpwnknndjoztjprfkkjopkdejofrfpkery";
    assert_eq!(pubkeys, expected_pubkeys);

    let signer = run_cli(&["generate", "signer", "--type", "ssh-ecdsa-p521", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_signer = "ur:signing-private-key/tanehnkkaotydpdpdpdpdpfwfeflgaglcxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkideofwjzidjtglknhsfxehjphthdjejyieimfefpfpfpfpfpfwfleckoidjngofpfpfpfpfeidjneskphtgyfpfpfpfpfpfpfpfpfpfwfpfpfpfpjpfpfpfpfpfwgljzhkeygmknhkgubkehknhsflfekkgshgecjoiaeogmktglghgaksfpfpfpfpfxflecjoiaeogmktglghgaksfpfpfpfpisgygyfwfxdygujkgaghenksiogykojpgweeehisgaiaetfyjydldlflfygefdfybkjtfefxfwhgeogyfliegugagojkhsguhdhgfpknfejnhskneyemfyeoihjsjsgsjeeeetghkkeogwecfgjkecjlenimiagljtemkngygrieglgdgsjnemgofpfwideoknidgrinfwfdhtbkeskojljogmesehecksghihjngtgugrfdjejyflkkgrjedngyisiyjtetiniegujthdgoidjphkiajyhtkkjkjegteekndljskteskpfdisihdydyhffyjzgoemjljzjseseoemjyfdesbkgtgakkglidgofefpfpfpfegaknkkeneekkjketkpkpgtjlfpfpfpfpghhthggljeiaeyfejyiaeyisisgtinehkphshdgldyiafygokkgtgyfpfpfpfpiskphshdgldyiafygokkgtgybkfpfpfpgagofefpgyjyfejpfxfednjkhkfegsenknkpglhkgufdgdfpemiydlksiokkgmktecksfpiohfjydyfwjtgoinfggsfljejzehiogtksgejnjkeskpkteseojsjsinecgwgdfebketjyknkpgmidgwhsgwjleofyhtdnetdyfxjtghghkkeckpehfpfphgeseteykkjliogmeyiyidengrgoiyieihiagoeojoimfeinisecgsgmjkinjogdjegahdecdlgajtgojoehehflbkeneyfdgshgiajpgefygwgtdlenjkgdidiseehdjyglfggyechfgwengehskoiednemgmdlghfxgtimhgehfwfpfpfpfpgyiofdjpjpjkjyeydydlhgideceskkemjpieehihflhsjyeybkjykphggeknisjliyjydlhskkkteyjeihjzfwgtkoiaisesfefgisktjofeesihfdkkksghiagyeegefwksgtieflfphkeedlioihgydlhgisengwjoiejseefpinjzgadnfpfpfpfpfpbkieimideyehjyhthgecdyfpgygafybkdpdpdpdpdpfeglfycxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkrevawsrl";
    assert_eq!(signer, expected_signer);

    let verifier = run_cli(&["generate", "verifier", &signer]).unwrap();
    let expected_verifier = "ur:signing-public-key/tanehskkadaaihiaiejkhsdpjkishseydpjtinjkjyjoeceyehcxfpfpfpfpfeeyhfimhtfdglisgshdgljlhkghgajyidjnjzkniefdfpehgtimfefpfpfpfpgaidjnjzkniefdfpehgtimfefpfpfpfxfgfwfpfegsgmgrktisgdjpflfwfxdnjkemimhgfeisknktgweodlethkgtjeiagwiagygafgidiefphtehgaisguksjogeiehkfygtguhtjpgdidjkgdieenjsjlkpghimksgdgsiaemjehgknjnimjsglkteyiykoglfpjodydyetkpidjygyfpfgkoiygljkjsgafeiejteydninjzfdeohdjtfgglenhkksgajlihgudyidgajsghecfxfgdniykkgeehgrieiegmkpjyiskkehjtgrkkgyknimgddnjpfyeyeeihfgemghgmgogwhfghkpinhgjpeoiykpdyiydyktimgaehjygygyfsfscxiajljnjnihjtjyfhayjkjn";
    assert_eq!(verifier, expected_verifier);

    let verifier = run_cli(&["generate", "verifier", expected_pubkeys]).unwrap();
    assert_eq!(verifier, expected_verifier);
}

// Particularly slow, so disabled by default.
#[test]
#[ignore]
fn test_ssh_dsa() {
    let pubkeys = run_cli(&["generate", "pubkeys", "--type", "ssh-dsa", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_pubkeys = "ur:crypto-pubkeys/lftanshftanehskkaoghjkjkisdpiejkjkcxfpfpfpfpfweoglknhsfxehjeiaeogtfpfpfpfxfwfpgdfwgretjtjphtjehdiyieksjykteygaingmhdhkiaimidemfyfghsfwjkiejzknhkjohgksghgmeyesjekkgygyfljyeyhkeneeinkseydndnfxjnfxjleeesgeesgygujofdkthgiohtgofgechffwhfgoghfyghflflksgdemksksfeguecihgsgudlhkiyiykpgmemethkhdiohtfeidfpguecjsidglidhdhkfdhkhtfehfhgiygwfdiyghjsgmfyfxgmgmjpjegageesgegoinjtflghfwglgedlgaknfydnjpihehendlfyieglgskkjnhfhtkteokpfxjyfpfpfpfpfggyfygofletgukkfeihdnfphgjtisgtjoiodlkkjykoglkpecgsktknetktfpfpfpgafwgmkogmiaehglhghthkjlgrfxfgetiegdhkgogrfghdhgfwhsjsinisgshfhsfdhsktiyisktfdjehdfpetjsisgaeskojsemgujoemhsdlkphsjnjziegmgskojlkofdfwkoecjlecgrgyfdjpguhgemiojlglfwidkkgafeenimjzfyisgweoiehfhgktfxinidjygufyfwiaksgegljyhggtgaetkoeejsiahkfgdnkpeekkjefgingmiajnfwjektgyjoihemgukngljlglfdhffxeyflfwgreoglfgjnimkniegeisfwhdgmenfyfdhkkseeecfpghieksihiofpfpfpgafefpjlidglfldlehidfpeekogseohdechtfdfyhthsgwfwetgmemjphdjohgihihgednishgfwkthsimfpfddlhgimiheoinjzehgljzjlgyihfeihgsiojpgwimjohfjnfgdldlidiagmisieiykkkofdghiygyjlgreyiokteseefgehgwiakphtghemktflkkgyeojzgdgahsjzgeehjejokngretjsdnimfygddngliagrhsgsioghinehimjsiagridglgukpfwfwjlineteyehfphdghimidhgeohkgdfghfhsenhfhdgwjtgtgmjnfwinjyjzjzfygrjoeyfyetfscxiajljnjnihjtjytansgrhdcxfdgwgacloxsrmupdcybdchfylewsdilrbestjodpwnknndjoztjprfkkjopkdejomsaadihh";
    assert_eq!(pubkeys, expected_pubkeys);

    let signer = run_cli(&["generate", "signer", "--type", "ssh-dsa", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_signer = "ur:signing-private-key/tanehnkkahhldpdpdpdpdpfwfeflgaglcxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkideofwjzidjtglknhsfxehjphthdjejyieimfefpfpfpfpfpfwfleckoidjngofpfpfpfpfeidjneskphtgyfpfpfpfpfpfpfpfpfpfwfpfpfpfwjkiofpfpfpfpiekniaeyiojyhtfdbkglknfpfpfpfpiogyfyktgukogeeneyhtfgeoeoiaidiaglingajehfeyfdgaeydnktkshgioidfdhtiaeygrhfjkgodyiekohtgtjefefwjpiejngwkpgajkiekokoiojoiojsgwgdgubkiygofejsgmetfgjlflhffwihhfgyhfhffektdyksisjkghdnetiagmfekphdindykoeyfdeoemjeihdlflfgeeflgmflktfekphsjnknhgeheyfweyflgmfghfjtkniseodyenjegyktbkjegohsecfxfxiyguhfgajoksjektghguiykkgtktdljseojyihkokteoghguetjojzhgiaglemiojpgyfpfpfpfwgofpehfwkofejkisfdkoiofgjoeeghgrhkgdetjpidknidkpguetbkgtdlgtfpfpfpfxfpgoiddyhdglghhfjnhggrfxioisiyfdgheyfgfxishfehiohgjsjljlguehhgiseyjkfdeeiafwecfgktgdgrjlgugdidenkpdyjsiheykoemjnjojohdgoguemenbkgsksktiddnhsgwgujefwendyjzkpeegrfygyhgetinfwgwjlecgyeeghjyeohfhfjkfpjljnemgoiokthdgtgughidhfimfxgdgsdngrjtflfwiyjpkpgtjofwhkjehdgeiohtgtfegrbkhdkpdyjkknhsfygmehgyjyisiogujykngmhtjleteoguhkgyhfdyihiokseygtihgwgyfeeoiahdjlfpfpfpfxfwfpgrflkngmkoeshgktgwgskkesehdnhggmkteyhgimioiyfeihenbkehenhfjtjtiniyjlhfioiafljlktfwdlehjleojyeejoieghhthsfefdisfdineegrknjlenhfhtisiydleyeofehkhdhdetjpksdyeodygrfxjyjlgtgdihfwieghjtgsjngodnetfwbkjkjeglecghkkfljoguiehtgriakkkogrkojlktkndlimhdfxjnineefeeejyhkenjtfxjnkngojpiogyhsgakogljygyfgdyeeeyehjyeyfykshfhgkpjzhfknjoknfehtiohkjphthtbkgykkjsieiodlfpfpfpfweegegtgegtfwgrghfxghfpgufpfpfpfpfweoglknhsfxehjeiaeogtfpfpfpfxfwfpgdfwgretjtjphtjehdiyieksjykteygaingmhdhkiaimidemfyfghsbkfwjkiejzknhkjohgksghgmeyesjekkgygyfljyeyhkeneeinkseydndnfxjnfxjleeesgeesgygujofdkthgiohtgofgechffwhfgoghfyghflflksgdemksksfeguecihgsgudlhkiybkiykpgmemethkhdiohtfeidfpguecjsidglidhdhkfdhkhtfehfhgiygwfdiyghjsgmfyfxgmgmjpjegageesgegoinjtflghfwglgedlgaknfydnjpihehendlfyieglgskkjnhfhtktbkeokpfxjyfpfpfpfpfggyfygofletgukkfeihdnfphgjtisgtjoiodlkkjykoglkpecgsktknetktfpfpfpgafwgmkogmiaehglhghthkjlgrfxfgetiegdhkgogrfghdhgfwhsjsinisbkgshfhsfdhsktiyisktfdjehdfpetjsisgaeskojsemgujoemhsdlkphsjnjziegmgskojlkofdfwkoecjlecgrgyfdjpguhgemiojlglfwidkkgafeenimjzfyisgweoiehfhgktfxinbkidjygufyfwiaksgegljyhggtgaetkoeejsiahkfgdnkpeekkjefgingmiajnfwjektgyjoihemgukngljlglfdhffxeyflfwgreoglfgjnimkniegeisfwhdgmenfyfdhkkseeecfpghbkieksihiofpfpfpgafefpjlidglfldlehidfpeekogseohdechtfdfyhthsgwfwetgmemjphdjohgihihgednishgfwkthsimfpfddlhgimiheoinjzehgljzjlgyihfeihgsiojpgwimbkjohfjnfgdldlidiagmisieiykkkofdghiygyjlgreyiokteseefgehgwiakphtghemktflkkgyeojzgdgahsjzgeehjejokngretjsdnimfygddngliagrhsgsioghinehimjsiagridbkglgukpfwfwjlineteyehfphdghimidhgeohkgdfghfhsenhfhdgwjtgtgmjnfwinjyjzjzfygrjoeyfyetfpfpfpfpgogygtgoflioesfxiefxiyeoeojzgejsfgetgsingdjyfpgmesbkgrjzdyfpfpfpfpfdhkeyesjyidhghfkpiefpfefxfpktfsfsbkdpdpdpdpdpfeglfycxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkkpsrguhk";
    assert_eq!(signer, expected_signer);

    let verifier = run_cli(&["generate", "verifier", &signer]).unwrap();
    let expected_verifier = "ur:signing-public-key/tanehskkaoghjkjkisdpiejkjkcxfpfpfpfpfweoglknhsfxehjeiaeogtfpfpfpfxfwfpgdfwgretjtjphtjehdiyieksjykteygaingmhdhkiaimidemfyfghsfwjkiejzknhkjohgksghgmeyesjekkgygyfljyeyhkeneeinkseydndnfxjnfxjleeesgeesgygujofdkthgiohtgofgechffwhfgoghfyghflflksgdemksksfeguecihgsgudlhkiyiykpgmemethkhdiohtfeidfpguecjsidglidhdhkfdhkhtfehfhgiygwfdiyghjsgmfyfxgmgmjpjegageesgegoinjtflghfwglgedlgaknfydnjpihehendlfyieglgskkjnhfhtkteokpfxjyfpfpfpfpfggyfygofletgukkfeihdnfphgjtisgtjoiodlkkjykoglkpecgsktknetktfpfpfpgafwgmkogmiaehglhghthkjlgrfxfgetiegdhkgogrfghdhgfwhsjsinisgshfhsfdhsktiyisktfdjehdfpetjsisgaeskojsemgujoemhsdlkphsjnjziegmgskojlkofdfwkoecjlecgrgyfdjpguhgemiojlglfwidkkgafeenimjzfyisgweoiehfhgktfxinidjygufyfwiaksgegljyhggtgaetkoeejsiahkfgdnkpeekkjefgingmiajnfwjektgyjoihemgukngljlglfdhffxeyflfwgreoglfgjnimkniegeisfwhdgmenfyfdhkkseeecfpghieksihiofpfpfpgafefpjlidglfldlehidfpeekogseohdechtfdfyhthsgwfwetgmemjphdjohgihihgednishgfwkthsimfpfddlhgimiheoinjzehgljzjlgyihfeihgsiojpgwimjohfjnfgdldlidiagmisieiykkkofdghiygyjlgreyiokteseefgehgwiakphtghemktflkkgyeojzgdgahsjzgeehjejokngretjsdnimfygddngliagrhsgsioghinehimjsiagridglgukpfwfwjlineteyehfphdghimidhgeohkgdfghfhsenhfhdgwjtgtgmjnfwinjyjzjzfygrjoeyfyetfscxiajljnjnihjtjycfeensbg";
    assert_eq!(verifier, expected_verifier);

    let verifier = run_cli(&["generate", "verifier", expected_pubkeys]).unwrap();
    assert_eq!(verifier, expected_verifier);
}

// Particularly slow, so disabled by default.
#[test]
#[ignore]
fn test_ssh_rsa_sha256() {
    let pubkeys = run_cli(&["generate", "pubkeys", "--type", "ssh-rsa-sha256", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_pubkeys = "ur:crypto-pubkeys/lftanshftanehskkadlrjkjkisdpjpjkhscxfpfpfpfpfweoglknhsfxehkkiaeyfefpfpfpfpfyfpgyfpfwfpfpfpfwfpgyfyjzktinkkdyhfishgdyhgfwfxhseejkfwidksjsfyidgojyenjsiheeenjsfgjogujnececjykkglgsjsideseyhkhsjkesfgiyjejnfekpgsiakofpgseheoeyeehdiahfdygefdgeioehfpidfxiaenjtiegejkeegahshtgrjyiehgjshgksgsdnemehineydyjkktinhtdlfgjngakoktgafefyfdgwgwgwhtjpidendygueyimhgfddngmhkgoesjlgedydnkseohkfygskkhkinhgjyesfxkogwiajogtisihkphdetehgtgtdyflhkjpfdjzjyiogoisisesktjtengrfgjyjeknjshsjnjlgaeninglfgjsgthfdyecglgegegreeimfygygahdjkiejldyjlfyetfygrimgagdihkohgjtguiofdisiofyjtfgidgmeednfxkphkendygtjoidesgogseoineoktflfykniyjnflingejtjeeokkioknidgoetjzesehengojeetgoihkoidfyhtecgojojokkeshdhdjnehiofefwdnfygyiejzkshthtgeknjeiyisfygufpdlksenghgdjojygteyioesgsetfdgugmeogejneeetjkgtecdnenjkjoehhdgsfwjeideyfdcxiajljnjnihjtjytansgrhdcxfdgwgacloxsrmupdcybdchfylewsdilrbestjodpwnknndjoztjprfkkjopkdejotpgdosen";
    assert_eq!(pubkeys, expected_pubkeys);

    let signer = run_cli(&["generate", "signer", "--type", "ssh-rsa-sha256", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_signer = "ur:signing-private-key/tanehnkkatbwdpdpdpdpdpfwfeflgaglcxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkideofwjzidjtglknhsfxehjphthdjejyieimfefpfpfpfpfpfwfleckoidjngofpfpfpfpfeidjneskphtgyfpfpfpfpfpfpfpfpfpfwfpfpfpfwfgktfpfpfpfpiekniaeyiojyiajtbkglisfpfpfpfpfpktfefpfpgyfpfpfpgyfefpeciagajkjyfghkhfjyfgiogyjnkpgsfphgethsioeyehgsihjsjtkpgwjsishsgojokpihidiaimguenjndliejnfljpgdgmhdecgeisbkgsineogsktfxesieeskpfgeofgiefxgmkkhkglgyflktjtgwjoeoguidgwfxfljngujphdhfjsjzjkgudlkpeshkjyjygsgtgajniykshtingsetfxfwfpksknimimjnhseydnjyfejybkjlehisdljehgfggdhsfxiegdjkieeyfpkketjngajzjpiygyjpknjtgrghgahdjpjzdlglghfyglfwjngrksecidhkfggahkiyiagedninisidhtgtenjnjojsfxgwjlimgmhsimfgiebkgwghgugugukpgaktdyfxfgemfdhsglgrfpdlfpkkjlkkfyeojpehjodyjlfweehkfpeckshgdyihgdiojpjngwjyfygrhgdlhffxeseejyetfwioeteoecisjlinhtecgletjlgteyehbkgdgeiyieihjzgegdfgfdjpeykteyihhfgrhsiakohfehecjyhkfwfpiyiodyfdhtiahghgguiaecfdeegydyiogdetihjeknenidghgljlgdgudlfwdyjeiekkhtkpgdgsfygwiykpjpbkgriehfkkkthtflesisktfpfpfpetfyhkghfykpdleyfektemkoktfpfpfpfpiekniaeyiojyiajtglisfpfpfpfwfpgyfyjzktinkkdyhfishgdyhgfwfxhseejkfwidksjsfyidgojybkenjsiheeenjsfgjogujnececjykkglgsjsideseyhkhsjkesfgiyjejnfekpgsiakofpgseheoeyeehdiahfdygefdgeioehfpidfxiaenjtiegejkeegahshtgrjyiehgjshgksgsdnbkemehineydyjkktinhtdlfgjngakoktgafefyfdgwgwgwhtjpidendygueyimhgfddngmhkgoesjlgedydnkseohkfygskkhkinhgjyesfxkogwiajogtisihkphdetehgtgtdyflhkjpbkfdjzjyiogoisisesktjtengrfgjyjeknjshsjnjlgaeninglfgjsgthfdyecglgegegreeimfygygahdjkiejldyjlfyetfygrimgagdihkohgjtguiofdisiofyjtfgidgmeednfxkpbkhkendygtjoidesgogseoineoktflfykniyjnflingejtjeeokkioknidgoetjzesehengojeetgoihkoidfyhtecgojojokkeshdhdjnehiofefwdnfygyiejzkshthtgeknjeiyisfybkgufpdlksenghgdjojygteyioesgsetfdgugmeogejneeetjkgtecdnenjkjoehhdgsfwjeideyfdfpfpfpfpfpktfefpfpgyfpfpfpgyfefpkpiygogleoenkpjofweodyidiheofxecbkgmiaenihehgtghihkkhfiahfjlieenfxehfpdnkkkshteyieksenkshggsgeingsisjtfdioguesgskofygyengehgetetinhtimjshkglflgyihinjpgdflhgiaksgsetgyglkngeksbkidfxeceeeyjketknesiygrkkflknemgtimenfdidgwfgfyknhgjeguioiygljtkojehfgwgrgdenfdhsgeisehdlihjljlgwkpengdgwjlhsfdjkesinihkkglgefwkpisjpetfwidjkbkkphgehhffeenkndlehguetiagwioghflgrjsgoimhgfejsfpgyenjkehioememhdjpjohfjskshfjsfljniydyfxflktgmhdfeenfpeciofweygtfejlehgyjtinjyglgwemimktknecbkkkinimetdngugmjejnfwihgtjlhsgmjeidgednenjykneoeejtkohkjeiehsfejtenfggsidgagrjlgrjkfgglgaesjsgskohsjofpecgthsechsemeyisjtjsehjkgsenfdjtgahkkkbkfxehetdnghfggwkpeofehgjtjpehehgeeegoguengsgejohsjeksgtinfdgtisimdlglguhkdygtkpjlisjydyisfpgyfpfpfpgafefpjefpdyinfegajektjofdiehsimjpghknemgrbkgeeydyhdktjnfdkpeyguhgjtesgtfxgletkkihdlihimhdioguetjtfgjyeshdiajtjtecjoiseeiajsimkpgsknenjygskkiajoeyjefwgegsiefwfwkpfygukkfwfxgefpihetghhfbkgljygegtjyideekkdngsfljzghecjtkodyfyguguiefwgyfydnhsiyghetflknfdfgeoiadyiygajyethsfdfxfxgajsididfyimecidihghidgtjoeogwfyjlglgaghgtehiefdihhtbkgldlgrkofeisgljnidhkhtdlktfpfpfpfxfwfpgdksimeyidkpidjogliafphkihghhkfpjeemkneskngajsesiejkjkgrgegtetgahtflfwfyimflhgfejokngykthsgshffwdngrhfbkeneyfxineeksjliafgesesesimeshshsjziejzdyjofpeofwgsiajyfdgohdjlendngujkjtjyjsfpiheoehhdjojsgtfpgdiojeghhffdgtisjneoemecgagseokkfxgygsfleciyeebkisihgojthgesjedlecjygsgdhggeglgljnidingmjyhghfjohkfdgljphtgaiohdgdjkjyfyghhgehjsjzgejnetgagmfdjngufwfpfpfpfpiogyfyjofxeoghjegteodleeimioktgabkjnkthtihkpgrfljzisknkpdlgoemiojkfximimgleefpeniahgfwgtioioeeeneofxgogljzfygeingwkkgogujzechkisjygyflehgogsflfdjnjthfimiekojlgujnfxiejskkkkghbkhgingehtjeimhkjsjodyjykpgddlfdguguieinhsemjyiaeygueekpjofgjtkkhdgudndnkpkoeefwhdgdingsgsjsgtemkoesidknehjejogdfgjojsdygdkkfxihidglehhshtemdlbkdyknjpecenguiaisetiaesiahseehddnfwktfpfpfpfpieimideyehjyhthgecdyfpgygafsbkdpdpdpdpdpfeglfycxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkjzdmdpmh";
    assert_eq!(signer, expected_signer);

    let verifier = run_cli(&["generate", "verifier", &signer]).unwrap();
    let expected_verifier = "ur:signing-public-key/tanehskkadlrjkjkisdpjpjkhscxfpfpfpfpfweoglknhsfxehkkiaeyfefpfpfpfpfyfpgyfpfwfpfpfpfwfpgyfyjzktinkkdyhfishgdyhgfwfxhseejkfwidksjsfyidgojyenjsiheeenjsfgjogujnececjykkglgsjsideseyhkhsjkesfgiyjejnfekpgsiakofpgseheoeyeehdiahfdygefdgeioehfpidfxiaenjtiegejkeegahshtgrjyiehgjshgksgsdnemehineydyjkktinhtdlfgjngakoktgafefyfdgwgwgwhtjpidendygueyimhgfddngmhkgoesjlgedydnkseohkfygskkhkinhgjyesfxkogwiajogtisihkphdetehgtgtdyflhkjpfdjzjyiogoisisesktjtengrfgjyjeknjshsjnjlgaeninglfgjsgthfdyecglgegegreeimfygygahdjkiejldyjlfyetfygrimgagdihkohgjtguiofdisiofyjtfgidgmeednfxkphkendygtjoidesgogseoineoktflfykniyjnflingejtjeeokkioknidgoetjzesehengojeetgoihkoidfyhtecgojojokkeshdhdjnehiofefwdnfygyiejzkshthtgeknjeiyisfygufpdlksenghgdjojygteyioesgsetfdgugmeogejneeetjkgtecdnenjkjoehhdgsfwjeideyfdcxiajljnjnihjtjywdurdkdy";
    assert_eq!(verifier, expected_verifier);

    let verifier = run_cli(&["generate", "verifier", expected_pubkeys]).unwrap();
    assert_eq!(verifier, expected_verifier);
}

// Particularly slow, so disabled by default.
#[test]
#[ignore]
fn test_ssh_rsa_sha512() {
    let pubkeys = run_cli(&["generate", "pubkeys", "--type", "ssh-rsa-sha512", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_pubkeys = "ur:crypto-pubkeys/lftanshftanehskkadlrjkjkisdpjpjkhscxfpfpfpfpfweoglknhsfxehkkiaeyfefpfpfpfpfyfpgyfpfwfpfpfpfwfpgyfyfdgukteygrfliegtfwiyhshfglgoimhfiodliejogsjlgaeyfyeogljnfdingrdlgsingwfwhdkogwjthkfydnksgsgdgakokkhtgwghkpeskshtfldlgsktknfpdyjkgrghghjsgsjnfyemimksgwhkfegufgfgenhkemeyetfwetjnjsenfgglflkkgekkgshgimfeemkneoieiyhkgwkkgtehgrghktgrfxfwiminhfemhtfwgmiyflfphfgljodydyglgogmeciaglhteofykndlgdknjnfwihdyjejpflgtgdeokpdykkgaiyjnfygrhtgufedliyeygrecgdkofygrdyjsfyknguhffdflgugrdyhgkpgokniegdjzidfdhsehdneyecidksfgdlhshsehhsidiyfyemgwiyhsiefegrgdhgihguiekokkhkfeeoeyfeknfygodlimgofdghjnemiajliakkemgmeeghgtesdnfefeiyeekkjzfgidinhkjphsjtjtfpgwfljykpfefgesgyfdenkojokkdyhtjkgagtesksiyjpjeioeejefpioiodnidjkimetgsdlgdeefwjsetguecgdececdlkojsgtisioiehkhtfxiajyjegoksgyeygljkgwkpihhsfyjkiohtihgahfcxiajljnjnihjtjytansgrhdcxfdgwgacloxsrmupdcybdchfylewsdilrbestjodpwnknndjoztjprfkkjopkdejovyotplpd";
    assert_eq!(pubkeys, expected_pubkeys);

    let signer = run_cli(&["generate", "signer", "--type", "ssh-rsa-sha256", "--comment", COMMENT, PRVKEYS]).unwrap();
    let expected_signer = "ur:signing-private-key/tanehnkkatbwdpdpdpdpdpfwfeflgaglcxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkideofwjzidjtglknhsfxehjphthdjejyieimfefpfpfpfpfpfwfleckoidjngofpfpfpfpfeidjneskphtgyfpfpfpfpfpfpfpfpfpfwfpfpfpfwfgktfpfpfpfpiekniaeyiojyiajtbkglisfpfpfpfpfpktfefpfpgyfpfpfpgyfefpeciagajkjyfghkhfjyfgiogyjnkpgsfphgethsioeyehgsihjsjtkpgwjsishsgojokpihidiaimguenjndliejnfljpgdgmhdecgeisbkgsineogsktfxesieeskpfgeofgiefxgmkkhkglgyflktjtgwjoeoguidgwfxfljngujphdhfjsjzjkgudlkpeshkjyjygsgtgajniykshtingsetfxfwfpksknimimjnhseydnjyfejybkjlehisdljehgfggdhsfxiegdjkieeyfpkketjngajzjpiygyjpknjtgrghgahdjpjzdlglghfyglfwjngrksecidhkfggahkiyiagedninisidhtgtenjnjojsfxgwjlimgmhsimfgiebkgwghgugugukpgaktdyfxfgemfdhsglgrfpdlfpkkjlkkfyeojpehjodyjlfweehkfpeckshgdyihgdiojpjngwjyfygrhgdlhffxeseejyetfwioeteoecisjlinhtecgletjlgteyehbkgdgeiyieihjzgegdfgfdjpeykteyihhfgrhsiakohfehecjyhkfwfpiyiodyfdhtiahghgguiaecfdeegydyiogdetihjeknenidghgljlgdgudlfwdyjeiekkhtkpgdgsfygwiykpjpbkgriehfkkkthtflesisktfpfpfpetfyhkghfykpdleyfektemkoktfpfpfpfpiekniaeyiojyiajtglisfpfpfpfwfpgyfyjzktinkkdyhfishgdyhgfwfxhseejkfwidksjsfyidgojybkenjsiheeenjsfgjogujnececjykkglgsjsideseyhkhsjkesfgiyjejnfekpgsiakofpgseheoeyeehdiahfdygefdgeioehfpidfxiaenjtiegejkeegahshtgrjyiehgjshgksgsdnbkemehineydyjkktinhtdlfgjngakoktgafefyfdgwgwgwhtjpidendygueyimhgfddngmhkgoesjlgedydnkseohkfygskkhkinhgjyesfxkogwiajogtisihkphdetehgtgtdyflhkjpbkfdjzjyiogoisisesktjtengrfgjyjeknjshsjnjlgaeninglfgjsgthfdyecglgegegreeimfygygahdjkiejldyjlfyetfygrimgagdihkohgjtguiofdisiofyjtfgidgmeednfxkpbkhkendygtjoidesgogseoineoktflfykniyjnflingejtjeeokkioknidgoetjzesehengojeetgoihkoidfyhtecgojojokkeshdhdjnehiofefwdnfygyiejzkshthtgeknjeiyisfybkgufpdlksenghgdjojygteyioesgsetfdgugmeogejneeetjkgtecdnenjkjoehhdgsfwjeideyfdfpfpfpfpfpktfefpfpgyfpfpfpgyfefpkpiygogleoenkpjofweodyidiheofxecbkgmiaenihehgtghihkkhfiahfjlieenfxehfpdnkkkshteyieksenkshggsgeingsisjtfdioguesgskofygyengehgetetinhtimjshkglflgyihinjpgdflhgiaksgsetgyglkngeksbkidfxeceeeyjketknesiygrkkflknemgtimenfdidgwfgfyknhgjeguioiygljtkojehfgwgrgdenfdhsgeisehdlihjljlgwkpengdgwjlhsfdjkesinihkkglgefwkpisjpetfwidjkbkkphgehhffeenkndlehguetiagwioghflgrjsgoimhgfejsfpgyenjkehioememhdjpjohfjskshfjsfljniydyfxflktgmhdfeenfpeciofweygtfejlehgyjtinjyglgwemimktknecbkkkinimetdngugmjejnfwihgtjlhsgmjeidgednenjykneoeejtkohkjeiehsfejtenfggsidgagrjlgrjkfgglgaesjsgskohsjofpecgthsechsemeyisjtjsehjkgsenfdjtgahkkkbkfxehetdnghfggwkpeofehgjtjpehehgeeegoguengsgejohsjeksgtinfdgtisimdlglguhkdygtkpjlisjydyisfpgyfpfpfpgafefpjefpdyinfegajektjofdiehsimjpghknemgrbkgeeydyhdktjnfdkpeyguhgjtesgtfxgletkkihdlihimhdioguetjtfgjyeshdiajtjtecjoiseeiajsimkpgsknenjygskkiajoeyjefwgegsiefwfwkpfygukkfwfxgefpihetghhfbkgljygegtjyideekkdngsfljzghecjtkodyfyguguiefwgyfydnhsiyghetflknfdfgeoiadyiygajyethsfdfxfxgajsididfyimecidihghidgtjoeogwfyjlglgaghgtehiefdihhtbkgldlgrkofeisgljnidhkhtdlktfpfpfpfxfwfpgdksimeyidkpidjogliafphkihghhkfpjeemkneskngajsesiejkjkgrgegtetgahtflfwfyimflhgfejokngykthsgshffwdngrhfbkeneyfxineeksjliafgesesesimeshshsjziejzdyjofpeofwgsiajyfdgohdjlendngujkjtjyjsfpiheoehhdjojsgtfpgdiojeghhffdgtisjneoemecgagseokkfxgygsfleciyeebkisihgojthgesjedlecjygsgdhggeglgljnidingmjyhghfjohkfdgljphtgaiohdgdjkjyfyghhgehjsjzgejnetgagmfdjngufwfpfpfpfpiogyfyjofxeoghjegteodleeimioktgabkjnkthtihkpgrfljzisknkpdlgoemiojkfximimgleefpeniahgfwgtioioeeeneofxgogljzfygeingwkkgogujzechkisjygyflehgogsflfdjnjthfimiekojlgujnfxiejskkkkghbkhgingehtjeimhkjsjodyjykpgddlfdguguieinhsemjyiaeygueekpjofgjtkkhdgudndnkpkoeefwhdgdingsgsjsgtemkoesidknehjejogdfgjojsdygdkkfxihidglehhshtemdlbkdyknjpecenguiaisetiaesiahseehddnfwktfpfpfpfpieimideyehjyhthgecdyfpgygafsbkdpdpdpdpdpfeglfycxgwgdfeglgugufdcxgdgmgahffpghfecxgrfehkdpdpdpdpdpbkjzdmdpmh";
    assert_eq!(signer, expected_signer);

    let verifier = run_cli(&["generate", "verifier", &signer]).unwrap();
    let expected_verifier = "ur:signing-public-key/tanehskkadlrjkjkisdpjpjkhscxfpfpfpfpfweoglknhsfxehkkiaeyfefpfpfpfpfyfpgyfpfwfpfpfpfwfpgyfyjzktinkkdyhfishgdyhgfwfxhseejkfwidksjsfyidgojyenjsiheeenjsfgjogujnececjykkglgsjsideseyhkhsjkesfgiyjejnfekpgsiakofpgseheoeyeehdiahfdygefdgeioehfpidfxiaenjtiegejkeegahshtgrjyiehgjshgksgsdnemehineydyjkktinhtdlfgjngakoktgafefyfdgwgwgwhtjpidendygueyimhgfddngmhkgoesjlgedydnkseohkfygskkhkinhgjyesfxkogwiajogtisihkphdetehgtgtdyflhkjpfdjzjyiogoisisesktjtengrfgjyjeknjshsjnjlgaeninglfgjsgthfdyecglgegegreeimfygygahdjkiejldyjlfyetfygrimgagdihkohgjtguiofdisiofyjtfgidgmeednfxkphkendygtjoidesgogseoineoktflfykniyjnflingejtjeeokkioknidgoetjzesehengojeetgoihkoidfyhtecgojojokkeshdhdjnehiofefwdnfygyiejzkshthtgeknjeiyisfygufpdlksenghgdjojygteyioesgsetfdgugmeogejneeetjkgtecdnenjkjoehhdgsfwjeideyfdcxiajljnjnihjtjywdurdkdy";
    assert_eq!(verifier, expected_verifier);

    // NOTE: Does not match for some reason. Requires investigation.
    // let verifier = run_cli(&["generate", "verifier", expected_pubkeys]).unwrap();
    // assert_eq!(verifier, expected_verifier);

    let verifier1 = run_cli(&["generate", "verifier", expected_pubkeys]).unwrap();
    let verifier2 = run_cli(&["generate", "verifier", expected_pubkeys]).unwrap();
    assert_eq!(verifier1, verifier2);
}
